upstream gunicorn_app {
    server 127.0.0.1:8080;
}

server {
    listen 80;
    server_name localhost;

    location /public/ {
        alias /mnt/d/prog-eng/2026-MAI-Backend-A-MARYAN/lab2;
        autoindex on;
    }

    location /gunicorn/ {
        proxy_pass http://gunicorn_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}